#!/bin/sh
#
# chkconfig: 345 90 90
# description: Starts Vanir GUI agent
#
# Source function library.
. /etc/rc.d/init.d/functions

start()
{
	echo -n $"Starting Vanir GUI agent:"
	rm -f /tmp/vanir-session-env /tmp/vanir-session-waiter
	# start console-kit-daemon
	/usr/bin/ck-list-sessions > /dev/null 2>&1
	# pretend tha user is at local console
	touch /var/run/console/user
	DISPLAY=:0 /usr/bin/vanir-gui 2> /var/log/vanir/gui-agent.log &
	export DISPLAY=:0
	success
	echo ""
	return 0
}

stop()
{
	echo -n "Stopping Vanir GUI agent:"
	killall vanir-gui && success || failure
	echo ""
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
